import 'package:flutter/material.dart';

const postalCodes = {
  "Perlis": [
    {"postCode": "1000", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1007", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1009", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1500", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1502", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1503", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1504", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1505", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1506", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1508", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1512", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1514", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1516", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1517", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1518", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1524", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1529", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1532", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1538", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1540", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1546", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1550", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1551", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1556", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1560", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1564", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1570", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1572", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1576", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1578", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1582", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1586", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1590", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1592", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1594", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1596", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1598", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1600", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1604", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1606", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1608", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1609", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1610", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1612", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1614", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1620", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1622", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1626", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1628", "city": "Kangar", "region": "Perlis"},
    {"postCode": "1630", "city": "Kangar", "region": "Perlis"}
  ],
  "Terengganu": [
    {"postCode": "20000", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20050", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20100", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20200", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20300", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20400", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20500", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20502", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20503", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20504", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20505", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20506", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20508", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20512", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20514", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20516", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20517", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20518", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20519", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20520", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20532", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20534", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20536", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20538", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20540", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20542", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20546", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20548", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20550", "city": "Kerteh", "region": "Terengganu"},
    {"postCode": "20551", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20552", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20554", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20556", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20560", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20564", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20566", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20568", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20570", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20572", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20576", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20578", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20582", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20586", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20590", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20592", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20596", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20600", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20604", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20606", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20608", "city": "—", "region": "Terengganu"},
    {"postCode": "20609", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20610", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20612", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20614", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20618", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20620", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20622", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20626", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20628", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20630", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20632", "city": "—", "region": "Terengganu"},
    {"postCode": "20646", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20648", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20656", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20658", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20660", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20661", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20662", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20664", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20668", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20670", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20672", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20673", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20674", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20676", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20680", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20690", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20698", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20700", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20710", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20720", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20900", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20902", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20904", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20906", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20908", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20910", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20912", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20914", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20916", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20918", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20920", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20922", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20924", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20926", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20928", "city": "Kuala Terengganu", "region": "Terengganu"},
    {"postCode": "20930", "city": "Kuala Terengganu", "region": "Terengganu"}
  ],
  "Kelantan": [
    {"postCode": "18300", "city": "Gua Musang", "region": "Kelantan"},
    {"postCode": "18400", "city": "—", "region": "Kelantan"},
    {"postCode": "18500", "city": "—", "region": "Kelantan"}
  ],
  "Perak": [
    {"postCode": "32900", "city": "Bota", "region": "Perak"},
    {"postCode": "33000", "city": "Bota", "region": "Perak"},
    {"postCode": "33007", "city": "Kuala Kangsar", "region": "Perak"},
    {"postCode": "33009", "city": "Kuala Kangsar", "region": "Perak"},
    {"postCode": "33010", "city": "Kuala Kangsar", "region": "Perak"},
    {"postCode": "33020", "city": "Kuala Kangsar", "region": "Perak"},
    {"postCode": "33030", "city": "Kuala Kangsar", "region": "Perak"},
    {"postCode": "33040", "city": "Kuala Kangsar", "region": "Perak"},
    {"postCode": "33100", "city": "Kroh", "region": "Perak"},
    {"postCode": "33200", "city": "Gerik", "region": "Perak"},
    {"postCode": "33300", "city": "Gerik", "region": "Perak"},
    {"postCode": "33310", "city": "Gerik", "region": "Perak"},
    {"postCode": "33320", "city": "Gerik", "region": "Perak"},
    {"postCode": "33400", "city": "Lenggong", "region": "Perak"},
    {"postCode": "33410", "city": "Lenggong", "region": "Perak"},
    {"postCode": "33420", "city": "Lenggong", "region": "Perak"},
    {"postCode": "33500", "city": "—", "region": "Perak"},
    {"postCode": "33600", "city": "—", "region": "Perak"},
    {"postCode": "33700", "city": "Padang Rengas", "region": "Perak"},
    {"postCode": "33800", "city": "—", "region": "Perak"},
    {"postCode": "34000", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34007", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34008", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34009", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34010", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34020", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34030", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34100", "city": "—", "region": "Perak"},
    {"postCode": "34120", "city": "—", "region": "Perak"},
    {"postCode": "34130", "city": "—", "region": "Perak"},
    {"postCode": "34140", "city": "—", "region": "Perak"},
    {"postCode": "34150", "city": "—", "region": "Perak"},
    {"postCode": "34200", "city": "Parit Buntar", "region": "Perak"},
    {"postCode": "34250", "city": "Tanjung Piandang", "region": "Perak"},
    {"postCode": "34300", "city": "Bagan Serai", "region": "Perak"},
    {"postCode": "34310", "city": "Bagan Serai", "region": "Perak"},
    {"postCode": "34350", "city": "—", "region": "Perak"},
    {"postCode": "34400", "city": "Simpang Empat (Semanggol), Perak", "region": "Perak"},
    {"postCode": "34500", "city": "—", "region": "Perak"},
    {"postCode": "34510", "city": "—", "region": "Perak"},
    {"postCode": "34520", "city": "—", "region": "Perak"},
    {"postCode": "34600", "city": "Kamunting", "region": "Perak"},
    {"postCode": "34650", "city": "—", "region": "Perak"},
    {"postCode": "34700", "city": "—", "region": "Perak"},
    {"postCode": "34750", "city": "Taiping, Perak", "region": "Perak"},
    {"postCode": "34800", "city": "Terong", "region": "Perak"},
    {"postCode": "34850", "city": "Changkat Jering", "region": "Perak"},
    {"postCode": "34900", "city": "Pantai Remis", "region": "Perak"},
    {"postCode": "34950", "city": "Bandar Baharu", "region": "Kedah"},
    {"postCode": "35000", "city": "Tapah", "region": "Perak"},
    {"postCode": "35007", "city": "Tapah", "region": "Perak"},
    {"postCode": "35009", "city": "Tapah", "region": "Perak"},
    {"postCode": "35300", "city": "Chenderiang", "region": "Perak"},
    {"postCode": "35350", "city": "Chenderiang", "region": "Perak"},
    {"postCode": "35400", "city": "Tapah Road", "region": "Perak"},
    {"postCode": "35500", "city": "Bidor", "region": "Perak"},
    {"postCode": "35600", "city": "Sungkai", "region": "Perak"},
    {"postCode": "35700", "city": "Trolak", "region": "Perak"},
    {"postCode": "35800", "city": "Slim River", "region": "Perak"},
    {"postCode": "35820", "city": "Slim River", "region": "Perak"},
    {"postCode": "35900", "city": "Tanjung Malim", "region": "Perak"},
    {"postCode": "35907", "city": "Tanjung Malim", "region": "Perak"},
    {"postCode": "35909", "city": "Tanjung Malim", "region": "Perak"},
    {"postCode": "35910", "city": "Tanjung Malim", "region": "Perak"},
    {"postCode": "35950", "city": "—", "region": "Perak"},
    {"postCode": "36000", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36007", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36008", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36009", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36010", "city": "—", "region": "Perak"},
    {"postCode": "36020", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36030", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36100", "city": "Bagan Datoh", "region": "—"},
    {"postCode": "36110", "city": "Teluk Intan", "region": "Perak"},
    {"postCode": "36200", "city": "—", "region": "Perak"},
    {"postCode": "36207", "city": "—", "region": "Perak"},
    {"postCode": "36209", "city": "—", "region": "Perak"},
    {"postCode": "36300", "city": "—", "region": "Perak"},
    {"postCode": "36307", "city": "—", "region": "Perak"},
    {"postCode": "36309", "city": "—", "region": "Perak"},
    {"postCode": "36400", "city": "Hutan Melintang", "region": "Perak"},
    {"postCode": "36500", "city": "—", "region": "Perak"},
    {"postCode": "36600", "city": "—", "region": "Perak"},
    {"postCode": "36700", "city": "Chikus", "region": "Perak"},
    {"postCode": "36750", "city": "Chikus", "region": "Perak"},
    {"postCode": "36800", "city": "—", "region": "Perak"},
    {"postCode": "36810", "city": "—", "region": "Perak"}
  ],
  "Pahang": [
    {"postCode": "39000", "city": "Tanah Rata", "region": "Pahang"},
    {"postCode": "39007", "city": "Tanah Rata", "region": "Pahang"},
    {"postCode": "39009", "city": "Tanah Rata", "region": "Pahang"},
    {"postCode": "39010", "city": "Tanah Rata", "region": "Pahang"},
    {"postCode": "39100", "city": "—", "region": "Pahang"},
    {"postCode": "39200", "city": "Ringlet, Malaysia", "region": "Pahang"},
    {"postCode": "28500", "city": "—", "region": "Pahang"},
    {"postCode": "28409", "city": "Mentakab", "region": "Pahang"},
    {"postCode": "28407", "city": "Mentakab", "region": "Pahang"},
    {"postCode": "28400", "city": "Mentakab", "region": "Pahang"},
    {"postCode": "28380", "city": "—", "region": "Pahang"},
    {"postCode": "28350", "city": "—", "region": "Pahang"},
    {"postCode": "28340", "city": "—", "region": "Pahang"},
    {"postCode": "28330", "city": "Teriang", "region": "Pahang"},
    {"postCode": "28320", "city": "Teriang", "region": "Pahang"},
    {"postCode": "28310", "city": "Teriang", "region": "Pahang"},
    {"postCode": "28300", "city": "Teriang", "region": "Pahang"},
    {"postCode": "28200", "city": "Teriang", "region": "Pahang"},
    {"postCode": "28100", "city": "—", "region": "Pahang"},
    {"postCode": "28050", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28040", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28030", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28020", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28010", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28009", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28007", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "28000", "city": "Temerloh", "region": "Pahang"},
    {"postCode": "27670", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27660", "city": "—", "region": "Pahang"},
    {"postCode": "27650", "city": "—", "region": "Pahang"},
    {"postCode": "27630", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27620", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27610", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27609", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27607", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27600", "city": "Raub District", "region": "Pahang"},
    {"postCode": "27500", "city": "—", "region": "Pahang"},
    {"postCode": "27400", "city": "—", "region": "Pahang"},
    {"postCode": "27310", "city": "Benta", "region": "Pahang"},
    {"postCode": "27300", "city": "Benta", "region": "Pahang"},
    {"postCode": "27210", "city": "Merapoh", "region": "Pahang"},
    {"postCode": "27209", "city": "Kuala Lipis", "region": "Pahang"},
    {"postCode": "27207", "city": "Kuala Lipis", "region": "Pahang"},
    {"postCode": "27200", "city": "Kuala Lipis", "region": "Pahang"},
    {"postCode": "27150", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27100", "city": "Kuala Lipis", "region": "Pahang"},
    {"postCode": "27090", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27070", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27060", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27050", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27040", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27030", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "27020", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27010", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "27000", "city": "Jerantut", "region": "Pahang"},
    {"postCode": "26900", "city": "—", "region": "Pahang"},
    {"postCode": "26820", "city": "Kuala Rompin", "region": "Pahang"},
    {"postCode": "26810", "city": "—", "region": "Pahang"},
    {"postCode": "26800", "city": "Kuala Rompin", "region": "Pahang"},
    {"postCode": "26700", "city": "—", "region": "Pahang"},
    {"postCode": "26690", "city": "—", "region": "Pahang"},
    {"postCode": "26680", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26660", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26650", "city": "—", "region": "Pahang"},
    {"postCode": "26640", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26630", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26620", "city": "—", "region": "Pahang"},
    {"postCode": "26610", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26609", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26607", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26600", "city": "Pekan", "region": "Pahang"},
    {"postCode": "26500", "city": "Maran", "region": "Pahang"},
    {"postCode": "26490", "city": "—", "region": "Pahang"},
    {"postCode": "26485", "city": "—", "region": "Pahang"},
    {"postCode": "26460", "city": "—", "region": "Pahang"},
    {"postCode": "26450", "city": "—", "region": "Pahang"},
    {"postCode": "26440", "city": "—", "region": "Pahang"},
    {"postCode": "26430", "city": "—", "region": "Pahang"},
    {"postCode": "26420", "city": "—", "region": "Pahang"},
    {"postCode": "26410", "city": "—", "region": "Pahang"},
    {"postCode": "26400", "city": "—", "region": "Pahang"},
    {"postCode": "26370", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26360", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26350", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26340", "city": "Endau", "region": "Johor"},
    {"postCode": "26330", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26320", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26310", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26300", "city": "Gambang, Pahang", "region": "Pahang"},
    {"postCode": "26250", "city": "—", "region": "Pahang"},
    {"postCode": "26200", "city": "Sungai Lembing", "region": "Pahang"},
    {"postCode": "26190", "city": "—", "region": "Pahang"},
    {"postCode": "26180", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26170", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26150", "city": "—", "region": "—"},
    {"postCode": "26140", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26100", "city": "—", "region": "Pahang"},
    {"postCode": "26090", "city": "—", "region": "Pahang"},
    {"postCode": "26080", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26070", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26060", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26050", "city": "—", "region": "Pahang"},
    {"postCode": "26040", "city": "Kuantan", "region": "Pahang"},
    {"postCode": "26030", "city": "—", "region": "Pahang"},
    {"postCode": "26020", "city": "—", "region": "Pahang"},
    {"postCode": "26010", "city": "Kuantan", "region": "Pahang"}
  ],
  "Selangor": [
    {"postCode": "40000", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "40100", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "40150", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "40160", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "40170", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "40200", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "40300", "city": "Shah Alam", "region": "Selangor"},
    {"postCode": "47301", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "47300", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "47200", "city": "Klang (city)", "region": "Selangor"},
    {"postCode": "47190", "city": "Kampong Petaling Bahagia", "region": "—"},
    {"postCode": "47180", "city": "Kampong Petaling Bahagia", "region": "—"},
    {"postCode": "47170", "city": "—", "region": "Selangor"},
    {"postCode": "47160", "city": "—", "region": "Selangor"},
    {"postCode": "47150", "city": "Putra Heights", "region": "Selangor"},
    {"postCode": "47140", "city": "Putra Heights", "region": "Selangor"},
    {"postCode": "47130", "city": "Puchong New Village", "region": "—"},
    {"postCode": "47120", "city": "—", "region": "Selangor"},
    {"postCode": "47110", "city": "Seri Kembangan", "region": "Selangor"},
    {"postCode": "47100", "city": "—", "region": "Selangor"},
    {"postCode": "47000", "city": "Sungai Buloh", "region": "—"},
    {"postCode": "46978", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46976", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46974", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46972", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46970", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46968", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46966", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46964", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46962", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46960", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46870", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46860", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46806", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46805", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46804", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46803", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46802", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46801", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46800", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46799", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46798", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46797", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46796", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46795", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46794", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46793", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46792", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46791", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46790", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46789", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46788", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46787", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46786", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46785", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46784", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46783", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46782", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46781", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46780", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46770", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46760", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46750", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46740", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46730", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46720", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46710", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46700", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46675", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46672", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46668", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46667", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46662", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46598", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46582", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46564", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46551", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46549", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46547", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46510", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46506", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46500", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46400", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46350", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46300", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46200", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46180", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46150", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46100", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46050", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "46000", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "45800", "city": "Kampong Dungun", "region": "Perak"},
    {"postCode": "45700", "city": "Bukit Rotan", "region": "—"},
    {"postCode": "45620", "city": "Bestari Jaya", "region": "Selangor"},
    {"postCode": "45609", "city": "Bestari Jaya", "region": "Selangor"},
    {"postCode": "45607", "city": "Bestari Jaya", "region": "Selangor"},
    {"postCode": "45600", "city": "Bestari Jaya", "region": "Selangor"},
    {"postCode": "45500", "city": "Kampung Tanjung Karang", "region": "Selangor"},
    {"postCode": "45400", "city": "Sekinchan", "region": "Selangor"},
    {"postCode": "45300", "city": "Sungai Besar", "region": "Selangor"},
    {"postCode": "45209", "city": "Sabak Bernam", "region": "Selangor"},
    {"postCode": "45207", "city": "Sabak Bernam", "region": "Selangor"},
    {"postCode": "45200", "city": "Sabak Bernam", "region": "Selangor"},
    {"postCode": "45150", "city": "Petaling Jaya", "region": "Selangor"},
    {"postCode": "45100", "city": "—", "region": "Selangor"},
    {"postCode": "45010", "city": "—", "region": "Selangor"},
    {"postCode": "45000", "city": "Kuala Selangor", "region": "Selangor"}
  ],
  "Kuala Lumpur": [
    {"postCode": "50744", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50746", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50748", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50750", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50752", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50754", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50758", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50760", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50762", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50764", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50766", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50768", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50770", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50772", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50774", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50776", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50778", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50780", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50782", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50784", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50786", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50788", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50790", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50792", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50794", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50796", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50798", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50800", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50802", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50804", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50806", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50808", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50810", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50812", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50814", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50816", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50818", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50901", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50902", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50903", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50904", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50906", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50907", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50908", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50909", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50910", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50911", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50912", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50913", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50914", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50915", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50916", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50917", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50918", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50919", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50920", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50921", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50922", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50923", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50924", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50925", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50926", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50927", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50928", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50929", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50930", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50931", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50932", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50933", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50934", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50935", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50936", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50937", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50938", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50939", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50940", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50941", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50942", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50943", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50944", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50945", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50946", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50947", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50948", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50949", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50950", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50988", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50989", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "50990", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "51000", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "51100", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "51200", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "51700", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "51990", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "52000", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "52100", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "52200", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "53000", "city": "Kuala Lumpur", "region": "Kuala Lumpur"},
    {"postCode": "53100", "city": "Kampung Sungai Pusu", "region": "—"},
    {"postCode": "53200", "city": "Kuala Lumpur", "region": "Kuala Lumpur"}
  ],
  "Johor": [
    {"postCode": "79000", "city": "Gelang Patah", "region": "Johor"},
    {"postCode": "79100", "city": "—", "region": "Johor"},
    {"postCode": "79150", "city": "Bandar Baru Selesa Jaya", "region": "Johor"},
    {"postCode": "79200", "city": "Gelang Patah", "region": "Johor"},
    {"postCode": "79250", "city": "—", "region": "Johor"},
    {"postCode": "79502", "city": "—", "region": "Johor"},
    {"postCode": "79503", "city": "—", "region": "Johor"},
    {"postCode": "79504", "city": "—", "region": "Johor"},
    {"postCode": "79505", "city": "—", "region": "Johor"},
    {"postCode": "79511", "city": "—", "region": "Johor"},
    {"postCode": "79513", "city": "—", "region": "Johor"},
    {"postCode": "79514", "city": "—", "region": "Johor"},
    {"postCode": "79517", "city": "—", "region": "Johor"},
    {"postCode": "79518", "city": "—", "region": "Johor"},
    {"postCode": "79520", "city": "—", "region": "—"},
    {"postCode": "79521", "city": "—", "region": "Johor"},
    {"postCode": "79523", "city": "—", "region": "Johor"},
    {"postCode": "79532", "city": "—", "region": "Johor"},
    {"postCode": "79538", "city": "—", "region": "Johor"},
    {"postCode": "79540", "city": "—", "region": "Johor"},
    {"postCode": "79546", "city": "—", "region": "Johor"},
    {"postCode": "79548", "city": "—", "region": "Johor"},
    {"postCode": "79550", "city": "—", "region": "Johor"},
    {"postCode": "79552", "city": "—", "region": "Johor"},
    {"postCode": "79555", "city": "—", "region": "Johor"},
    {"postCode": "79570", "city": "Alor Setar", "region": "Kedah"},
    {"postCode": "79575", "city": "—", "region": "Johor"},
    {"postCode": "79576", "city": "—", "region": "Johor"},
    {"postCode": "79592", "city": "—", "region": "Johor"},
    {"postCode": "79601", "city": "—", "region": "Johor"},
    {"postCode": "79603", "city": "—", "region": "Johor"},
    {"postCode": "79605", "city": "—", "region": "Johor"},
    {"postCode": "79606", "city": "—", "region": "Johor"},
    {"postCode": "79612", "city": "—", "region": "Johor"},
    {"postCode": "79626", "city": "—", "region": "Johor"},
    {"postCode": "79630", "city": "—", "region": "Johor"},
    {"postCode": "79632", "city": "—", "region": "Johor"},
    {"postCode": "79646", "city": "—", "region": "Johor"},
    {"postCode": "79658", "city": "—", "region": "Johor"},
    {"postCode": "79660", "city": "—", "region": "Johor"},
    {"postCode": "79680", "city": "—", "region": "Johor"},
    {"postCode": "79681", "city": "—", "region": "Johor"},
    {"postCode": "79683", "city": "—", "region": "Johor"},
    {"postCode": "80000", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80050", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80100", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80150", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80200", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80250", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80300", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80350", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80400", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80500", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80506", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80508", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80516", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80519", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80534", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80536", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80542", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80546", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80558", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80560", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80564", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80568", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80578", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80584", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80586", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80590", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80592", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80594", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80596", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80600", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80604", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80608", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80620", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80622", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80628", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80644", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80648", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80662", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80664", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80668", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80670", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80672", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80673", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80676", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80700", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80710", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80720", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80730", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80900", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80902", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80904", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80906", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80908", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80988", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "80990", "city": "Johor Bahru", "region": "Johor"},
    {"postCode": "81000", "city": "Kulai", "region": "Johor"}
  ],
  "Malacca": [
    {"postCode": "78309", "city": "Masjid Tanah", "region": "Malacca"}
  ],
  "Sabah": [
    {"postCode": "89858", "city": "Sipitang", "region": "Sabah"},
    {"postCode": "89859", "city": "Sipitang", "region": "Sabah"},
    {"postCode": "89900", "city": "Tenom", "region": "Sabah"},
    {"postCode": "89907", "city": "Tenom", "region": "Sabah"},
    {"postCode": "89908", "city": "Tenom", "region": "Sabah"},
    {"postCode": "89909", "city": "Tenom", "region": "Sabah"},
    {"postCode": "89950", "city": "—", "region": "Sabah"},
    {"postCode": "89957", "city": "—", "region": "Sabah"},
    {"postCode": "89958", "city": "—", "region": "Sabah"},
    {"postCode": "89959", "city": "—", "region": "Sabah"},
    {"postCode": "90000", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90007", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90008", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90009", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90100", "city": "Beluran", "region": "Sabah"},
    {"postCode": "90107", "city": "Beluran", "region": "Sabah"},
    {"postCode": "90109", "city": "Beluran", "region": "Sabah"},
    {"postCode": "90200", "city": "—", "region": "Sabah"},
    {"postCode": "90300", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90307", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90400", "city": "—", "region": "Sabah"},
    {"postCode": "90500", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90700", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90701", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90702", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90703", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90704", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90705", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90706", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90707", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90708", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90709", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90711", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90712", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90713", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90714", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90715", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90716", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90717", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90718", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90719", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90720", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90721", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90722", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90723", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90724", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90725", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90726", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90727", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90728", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90729", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90730", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90731", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90732", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90733", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90734", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90735", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90736", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90737", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90738", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90739", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90740", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "90741", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "91000", "city": "—", "region": "Sabah"},
    {"postCode": "91007", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91008", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91009", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91010", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91011", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91012", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91013", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91014", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91015", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91016", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91017", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91018", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91019", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91020", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91021", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91022", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91023", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91024", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91025", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91026", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91027", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91028", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91029", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91030", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91031", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91032", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91033", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91034", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91035", "city": "Tawau", "region": "Sabah"},
    {"postCode": "91100", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "91109", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "91110", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "91111", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "91112", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "91113", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "91114", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "88806", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88805", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88804", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88803", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88802", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88801", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88800", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88790", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88789", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88788", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88787", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88786", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88785", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88784", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88783", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88782", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88781", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88780", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88779", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88778", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88777", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88776", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88775", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88774", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88773", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88772", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88771", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88770", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88769", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88768", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88767", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88766", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88765", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88764", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88763", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88762", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88761", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88760", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88759", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88758", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88757", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88740", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88725", "city": "—", "region": "Sabah"},
    {"postCode": "88724", "city": "—", "region": "Sabah"},
    {"postCode": "88723", "city": "—", "region": "Sabah"},
    {"postCode": "88722", "city": "Putatan", "region": "Sabah"},
    {"postCode": "88721", "city": "—", "region": "Sabah"},
    {"postCode": "88700", "city": "—", "region": "Sabah"},
    {"postCode": "88690", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88680", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88676", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88675", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88673", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88672", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88670", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88662", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88661", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88660", "city": "—", "region": "Sabah"},
    {"postCode": "88658", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88656", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88648", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88646", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88644", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88634", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88632", "city": "Ranau", "region": "Sabah"},
    {"postCode": "88630", "city": "Sandakan", "region": "Sabah"},
    {"postCode": "88628", "city": "Lahad Datu", "region": "Sabah"},
    {"postCode": "88626", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88624", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88622", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88621", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88620", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88618", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88617", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88614", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88612", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88610", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88609", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88608", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88606", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88604", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88602", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88600", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88598", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88596", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88594", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88592", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88590", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88586", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88582", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88580", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88576", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88572", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88570", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88568", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88566", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88564", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88562", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88560", "city": "Kota Kinabalu", "region": "Sabah"},
    {"postCode": "88558", "city": "—", "region": "Sabah"}
  ],
  "Negeri Sembilan": [
    {"postCode": "72107", "city": "Bahau", "region": "Negeri Sembilan"},
    {"postCode": "72100", "city": "Bahau", "region": "Negeri Sembilan"},
    {"postCode": "72009", "city": "Kuala Pilah", "region": "Negeri Sembilan"},
    {"postCode": "72007", "city": "Kuala Pilah", "region": "Negeri Sembilan"},
    {"postCode": "72000", "city": "Kuala Pilah", "region": "Negeri Sembilan"},
    {"postCode": "71960", "city": "Port Dickson", "region": "Negeri Sembilan"},
    {"postCode": "71950", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "71909", "city": "Labu, Negeri Sembilan", "region": "Negeri Sembilan"},
    {"postCode": "71907", "city": "Labu, Negeri Sembilan", "region": "Negeri Sembilan"},
    {"postCode": "71900", "city": "Labu, Negeri Sembilan", "region": "Negeri Sembilan"},
    {"postCode": "71809", "city": "Kampung Baharu Nilai", "region": "Negeri Sembilan"},
    {"postCode": "71807", "city": "Kampung Baharu Nilai", "region": "Negeri Sembilan"},
    {"postCode": "71800", "city": "Kampung Baharu Nilai", "region": "Negeri Sembilan"},
    {"postCode": "71770", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "71760", "city": "Putrajaya", "region": "Putrajaya"},
    {"postCode": "71759", "city": "Kampong Lenggeng", "region": "Negeri Sembilan"},
    {"postCode": "71750", "city": "—", "region": "Negeri Sembilan"},
    {"postCode": "71709", "city": "Kampong Lenggeng", "region": "Negeri Sembilan"},
    {"postCode": "71707", "city": "Kampong Lenggeng", "region": "Negeri Sembilan"},
    {"postCode": "71700", "city": "—", "region": "Negeri Sembilan"},
    {"postCode": "71659", "city": "Kuala Klawang", "region": "Negeri Sembilan"},
    {"postCode": "71650", "city": "Kuala Klawang", "region": "Negeri Sembilan"},
    {"postCode": "71609", "city": "Kuala Klawang", "region": "Negeri Sembilan"},
    {"postCode": "71600", "city": "Kuala Klawang", "region": "Negeri Sembilan"},
    {"postCode": "71559", "city": "Tanjung Ipoh", "region": "Negeri Sembilan"},
    {"postCode": "71550", "city": "Tanjung Ipoh", "region": "Negeri Sembilan"},
    {"postCode": "71509", "city": "Tanjung Ipoh", "region": "Negeri Sembilan"},
    {"postCode": "71500", "city": "Tanjung Ipoh", "region": "Negeri Sembilan"},
    {"postCode": "71459", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "71450", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "71409", "city": "Rembau", "region": "Negeri Sembilan"},
    {"postCode": "71400", "city": "Rembau", "region": "Negeri Sembilan"},
    {"postCode": "71359", "city": "Kota, Negeri Sembilan", "region": "Negeri Sembilan"},
    {"postCode": "71350", "city": "Kota, Negeri Sembilan", "region": "Negeri Sembilan"},
    {"postCode": "71309", "city": "Rembau", "region": "Negeri Sembilan"},
    {"postCode": "71300", "city": "Rembau", "region": "Negeri Sembilan"},
    {"postCode": "71259", "city": "Tanjung Tuan", "region": "—"},
    {"postCode": "71250", "city": "—", "region": "—"},
    {"postCode": "71209", "city": "Rantau", "region": "Negeri Sembilan"},
    {"postCode": "71200", "city": "Rantau", "region": "Negeri Sembilan"},
    {"postCode": "71159", "city": "Linggi", "region": "Negeri Sembilan"},
    {"postCode": "71150", "city": "Linggi", "region": "Negeri Sembilan"},
    {"postCode": "71109", "city": "Rantau", "region": "Negeri Sembilan"},
    {"postCode": "71100", "city": "Rantau", "region": "Negeri Sembilan"},
    {"postCode": "71059", "city": "Tanjung Tuan", "region": "—"},
    {"postCode": "71050", "city": "—", "region": "Negeri Sembilan"},
    {"postCode": "71010", "city": "Rantau", "region": "Negeri Sembilan"},
    {"postCode": "71009", "city": "Port Dickson", "region": "Negeri Sembilan"},
    {"postCode": "71007", "city": "Port Dickson", "region": "Negeri Sembilan"},
    {"postCode": "71000", "city": "Port Dickson", "region": "Negeri Sembilan"},
    {"postCode": "70990", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70750", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70740", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70730", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70720", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70710", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70700", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70690", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70676", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70674", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70673", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70672", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70670", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70664", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70658", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70648", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70646", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70644", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70634", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70632", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70628", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70626", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70620", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70610", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70609", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70608", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70606", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70604", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70600", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70596", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70594", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70592", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70590", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70586", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70582", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70578", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70576", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70572", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70570", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70564", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70560", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70558", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70551", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70550", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70548", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70546", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70540", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70536", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70534", "city": "Seremban", "region": "Negeri Sembilan"},
    {"postCode": "70532", "city": "Seremban", "region": "Negeri Sembilan"}
  ],
  "Sarawak": [
    {"postCode": "98859", "city": "Lawas", "region": "Sarawak"},
    {"postCode": "98857", "city": "Lawas", "region": "Sarawak"},
    {"postCode": "98850", "city": "Lawas", "region": "Sarawak"},
    {"postCode": "98800", "city": "Lawas", "region": "Sarawak"},
    {"postCode": "98750", "city": "—", "region": "Sarawak"},
    {"postCode": "98709", "city": "—", "region": "Sarawak"},
    {"postCode": "98708", "city": "—", "region": "Sarawak"},
    {"postCode": "98707", "city": "Limbang", "region": "Sarawak"},
    {"postCode": "98700", "city": "Limbang", "region": "Sarawak"},
    {"postCode": "98300", "city": "—", "region": "Sarawak"},
    {"postCode": "98200", "city": "—", "region": "Sarawak"},
    {"postCode": "98159", "city": "Bekenu", "region": "Sarawak"},
    {"postCode": "98157", "city": "Bekenu", "region": "Sarawak"},
    {"postCode": "98150", "city": "Bekenu", "region": "Sarawak"},
    {"postCode": "98109", "city": "Miri, Malaysia", "region": "Sarawak"},
    {"postCode": "98107", "city": "Miri, Malaysia", "region": "Sarawak"},
    {"postCode": "98100", "city": "—", "region": "Sarawak"},
    {"postCode": "98059", "city": "—", "region": "Sarawak"},
    {"postCode": "98058", "city": "—", "region": "Sarawak"},
    {"postCode": "98057", "city": "—", "region": "Sarawak"},
    {"postCode": "98050", "city": "Marudi, Sarawak", "region": "Sarawak"},
    {"postCode": "98009", "city": "Miri, Malaysia", "region": "Sarawak"},
    {"postCode": "98008", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "98007", "city": "Miri, Malaysia", "region": "Sarawak"},
    {"postCode": "98000", "city": "Miri, Malaysia", "region": "Sarawak"},
    {"postCode": "97300", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97200", "city": "Tatau", "region": "Sarawak"},
    {"postCode": "97100", "city": "—", "region": "Sarawak"},
    {"postCode": "97015", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97014", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97013", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97012", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97011", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97010", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97009", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97008", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97007", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "97000", "city": "Bintulu", "region": "Sarawak"},
    {"postCode": "96900", "city": "—", "region": "Sarawak"},
    {"postCode": "96850", "city": "Song, Sarawak", "region": "Sarawak"},
    {"postCode": "96809", "city": "—", "region": "Sarawak"},
    {"postCode": "96807", "city": "—", "region": "Sarawak"},
    {"postCode": "96800", "city": "—", "region": "Sarawak"},
    {"postCode": "96709", "city": "Kanowit", "region": "Sarawak"},
    {"postCode": "96707", "city": "Kanowit", "region": "Sarawak"},
    {"postCode": "96700", "city": "Kanowit", "region": "Sarawak"},
    {"postCode": "96600", "city": "Julau", "region": "Sarawak"},
    {"postCode": "96510", "city": "Pakan, Sarawak", "region": "Sarawak"},
    {"postCode": "96509", "city": "—", "region": "Sarawak"},
    {"postCode": "96508", "city": "—", "region": "Sarawak"}
  ],
  "Labuan": [
    {"postCode": "87000", "city": "Labuan", "region": "0"},
    {"postCode": "87010", "city": "Labuan", "region": "0"},
    {"postCode": "87011", "city": "Labuan", "region": "0"},
    {"postCode": "87012", "city": "Labuan", "region": "0"},
    {"postCode": "87013", "city": "Labuan", "region": "0"},
    {"postCode": "87014", "city": "Labuan", "region": "0"},
    {"postCode": "87015", "city": "Labuan", "region": "0"},
    {"postCode": "87016", "city": "Labuan", "region": "0"},
    {"postCode": "87017", "city": "Labuan", "region": "0"},
    {"postCode": "87018", "city": "Labuan", "region": "0"},
    {"postCode": "87019", "city": "Labuan", "region": "0"},
    {"postCode": "87020", "city": "Labuan", "region": "0"},
    {"postCode": "87021", "city": "Labuan", "region": "0"},
    {"postCode": "87022", "city": "Labuan", "region": "0"},
    {"postCode": "87023", "city": "Labuan", "region": "0"},
    {"postCode": "87024", "city": "Labuan", "region": "0"},
    {"postCode": "87025", "city": "Labuan", "region": "0"},
    {"postCode": "87026", "city": "Labuan", "region": "0"},
    {"postCode": "87027", "city": "Labuan", "region": "0"},
    {"postCode": "87028", "city": "Labuan", "region": "0"},
    {"postCode": "87029", "city": "Labuan", "region": "0"},
    {"postCode": "87030", "city": "Labuan", "region": "0"},
    {"postCode": "87031", "city": "Labuan", "region": "0"},
    {"postCode": "87032", "city": "Labuan", "region": "0"},
    {"postCode": "87033", "city": "Labuan", "region": "0"}
  ],
};

final states = postalCodes.keys.toList();
get stateItems {
  var returns = states.map((e) => DropdownMenuItem(value: e, child: Text(e))).toList();
  returns.add(const DropdownMenuItem(child: Text('Not Selected')));
  return returns;
}

getCities(state) {
  Set<String> cities = {};
  for (var element in (postalCodes[state] ?? [])) {
    cities.add(element["city"]);
  }
  var returns = cities.map((e) => DropdownMenuItem(value: e, child: Text(e))).toList();
  returns.add(const DropdownMenuItem(child: Text('Not Selected')));
  return returns;
}
