// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8ZXmx3Nghu6ki48jmrGtby9Ip5gNmrM',
    appId: '1:485646374634:android:3e35e74fe0ef8b14bae993',
    messagingSenderId: '485646374634',
    projectId: 'school-app-aed59',
    databaseURL: 'https://school-app-aed59-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-aed59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyiMCnESLdQZx4uk9YxZxhWh4P6clxxo',
    appId: '1:485646374634:ios:0bd20e6abca163ebbae993',
    messagingSenderId: '485646374634',
    projectId: 'school-app-aed59',
    databaseURL: 'https://school-app-aed59-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-aed59.appspot.com',
    iosClientId: '485646374634-79srftmumsruft5ur92mh2qgpr01rogl.apps.googleusercontent.com',
    iosBundleId: 'com.grasp.saintSchoolparentPro',
  );
}
