// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG8ZXmx3Nghu6ki48jmrGtby9Ip5gNmrM',
    appId: '1:485646374634:android:9c873fabe2b4eb05bae993',
    messagingSenderId: '485646374634',
    projectId: 'school-app-aed59',
    databaseURL: 'https://school-app-aed59-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-aed59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyiMCnESLdQZx4uk9YxZxhWh4P6clxxo',
    appId: '1:485646374634:ios:ff3b2cfae4047ee0bae993',
    messagingSenderId: '485646374634',
    projectId: 'school-app-aed59',
    databaseURL: 'https://school-app-aed59-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-aed59.appspot.com',
    iosClientId: '485646374634-qka9tlajb0fn6c2cri8f9oti65bihj3t.apps.googleusercontent.com',
    iosBundleId: 'com.digisailor.saintSchoolParent',
  );
}
